### ISSUE TITLE
Multithreading Support?

### ISSUE THREAD

**Issue by jon-chuang** [lakwet/voracious_sort#1]
Hi, could you please give some guidance on adding multithreading support for the sorts? I just need some advice on which algos might be most productive and what to pay attention to in terms of cache etc.

**Comment by lakwet** [comment]
Hello I just release the multithread version: https://crates.io/crates/voracious_radix_sort

About multithread sort:
https://github.com/lakwet/voracious_sort#for-developers-and-researchers

**Comment by jon-chuang** [comment]
Very cool! I see there are some issues that could use some hands. Hopefully I can contribute. Btw, would the sorts benefit if you limit the number of for the keys?

**Comment by jon-chuang** [comment]
One other thing I would like to do is to try to reduce the cache footprint of the dlsd_radixsort for multiple concurrent sorts on all available threads.

**Comment by lakwet** [comment]
PR are opened
