### ISSUE TITLE
'Almost descending' benchmark is actually almost ascending

### ISSUE THREAD

**Issue by NicholasGorski** [lakwet/voracious_sort#13]
For reference, from `helper_random_array_almost_desc_u32`:

```rust
    let mut array = helper_random_array_descending_u32(size);
    array.reverse();

    for _ in 0..((size as f64).log2() as usize) {
        let i = rng.gen_range(0, size);
        let j = rng.gen_range(0, size);
        array.swap(i, j);
    }
```

The `array.reverse()` undoes the reversal in `helper_random_array_descending_u32`; looks like this ends up being equivalent to `helper_random_array_almost_asc_u32`?

**Comment by lakwet** [comment]
Oh yes, indeed, thanks you

**Comment by lakwet** [comment]
It should be fixed, but I haven't re run the benchmarks.

[Commit](https://github.com/lakwet/voracious_sort/commit/dee7e5856df374521c98e5232ffcf7d2e5858af5)
