### ISSUE TITLE
Slow compilation time

### ISSUE THREAD

**Issue by jon-chuang** [lakwet/voracious_sort#5]
should investigate why. Not using much macros or trait specialisation right? Maybe check if using foo::*; and instead use features for gated compilation?

**Comment by lakwet** [comment]
if you run the speed test, you can comment all the other tests (in the mod file), it is way faster to compile
speed test are commented in the repo

it is not a small repo, and with traits, there are a lot au code to optimize

btw i use the master branch as the last released version
there is one branch by released version

the working branch is the "dev" branch

**Comment by lakwet** [comment]
I am adding Rust "feature" so in the next version (coming soon) you will be able to use only the single thread sort without having to compile the code of the multithread sort and its dependency.
This should be faster.
I hope I will be able to release the v1.1.0 as soon as possible.

**Comment by jon-chuang** [comment]
I think making the rayon dependency optional on that feature would also be nice, as our code base using voracious has a no_std compilation mode.

**Comment by lakwet** [comment]
version 1.1.0 is release, you can use single thread sort without having to build rayon as dependency
https://crates.io/crates/voracious_radix_sort
